### PR TITLE
fix: upload resources using digest in upload-charm

### LINKED ISSUE #67: `charmcraft upload-resource` (v2.1.0) requires images to be passed by digest, not tagged image name
### Bug Description

Charmcraft's `charmcraft upload-resource` by design requires any image to be upload be specified [by digest](https://discourse.charmhub.io/t/charmcrafts-upload-resource-command/4580), not by image name.  In charmcraft <=2.1.0, `charmcraft upload-resource` did not check for this and by chance used the input in a way that successfully uploaded the image even though it was not specified by digest.  

Charmcraft 2.1.0 [fixes a bug in handling image digests](https://github.com/canonical/charmcraft/pull/871) in a way that 
breaks using tagged images (specifically, charmcraft treats any input with a `:` as a digest, like `sha256:digest`).  This means the upload-charm action fails because it provides an image name instead of a digest.

### To Reproduce

Use upload-action in any CI with charmcraft >2.1.0

### Environment

Github runners

### Relevant log output

```shell
Example of failure: https://github.com/canonical/kubeflow-profiles-operator/actions/runs/3235732172/jobs/5300571800
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ca-scribner**
This change adds a step of extracting an image's digest from
docker and then calling `charmcraft upload-resource`
with that digest rather than the image name.
This conforms with charmcraft's expected usage:
https://discourse.charmhub.io/t/charmcrafts-upload-resource-command/4580

Fixes #67

[This action run](https://github.com/canonical/kubeflow-profiles-operator/actions/runs/3236847794/jobs/5305642876) from kubeflow-profiles-operator gives an example of this action working (CI is pinned to this PR's branch).  Previous to this PR, [the action would fail](https://github.com/canonical/kubeflow-profiles-operator/actions/runs/3236834548/jobs/5303166564).

### CODE REVIEW

File: src/services/charmcraft/charmcraft.ts [hunk 1]
```diff
@@ -115,13 +116,39 @@ class Charmcraft {
       throw new Error('Could not pull the docker image.');
     }
 
+    // strip any repository details from the image name, as this will confuse `docker image ls`
+    const resourceImageNameOnly = getImageName(resource_image);
+
+    const result = await getExecOutput(
```
Comment (agathanatasha) [inline src/services/charmcraft/charmcraft.ts:122]: I would prefer to have this block in docker.ts, since it's a more docker specific operation. Otherwise, LGTM

**Review by agathanatasha — CHANGES_REQUESTED** [review]

File: src/services/charmcraft/charmcraft.ts (hunk 1 above)
Comment (ca-scribner) [reply src/services/charmcraft/charmcraft.ts]: good point.  Moved that into the helper

**Review by agathanatasha — APPROVED** [review]
