### PR TITLE
fix(upload-bundle): Implement the same functionality without using `juju-bundle`

### LINKED ISSUE #23: Move away from using juju-bundle
> Just a note for @DomFleischmann that we need to think 
> carefully about using this, and what the succession plan is > for that tool now that Ken has likely stopped maintaining it.

_Originally posted by @jnsgruk in https://github.com/canonical/charmhub-upload-action/pull/21#discussion_r808004897_

### PR DESCRIPTION
**Pull request by mvlassis**
Closes #23 and #150.

This PR updates the `upload-bundle` action to decouple from the `juju-bundle` executable, found [here](https://github.com/canonical/juju-bundle). 

Essentially, the action now calls `charmcraft pack` on the bundle.yaml file's directory, captures the output to get the filename of the `.zip` bundle file, and then calls `charmcraft upload` for the appropriate channel and using the credentials in `$CHARMCRAFT_AUTH`.

Note that for some reason, all the output in the `charmcraft pack` executable is always on stderr, and not on stdout.

Here is an [example run](https://github.com/canonical/bundle-kubeflow/actions/runs/10578537130) using the action here.

### CODE REVIEW

File: src/services/bundle/bundle.ts [hunk 1]
```diff
@@ -5,13 +5,28 @@ class Bundle {
...
+        const bundleName = lastLine.split(' ')[1];
+        await exec.exec('charmcraft', [
+          'upload',
+          bundleName,
+          '--release',
+          channel,
+        ]);
+      } else {
+        throw new Error(
+          'Failed to extract the bundle name from the output of charmcraft pack.',
```
Comment (orfeas-k) [inline src/services/bundle/bundle.ts:22]: If `lastLine` is empty, I think it probably means that there is no stderr captured when running charmcraft pack, right? Maybe mentioning that it "Failed to extract the bundle name from output" is a bit misleading.

On a second thought, this is not entirely false, since there is no output, thus we indeed failed to extract it. Do you think it would make sense to clarify this error message a bit more?

**Review by orfeas-k — COMMENTED** [review]
Good job @mvlassis ! Left some comments

File: src/services/bundle/bundle.ts [hunk 2]
```diff
@@ -5,13 +5,28 @@ class Bundle {
...
     process.chdir(path);
-    await exec.exec('juju-bundle', [
-      'publish',
-      '--destructive-mode',
-      '--serial',
-      '--release',
-      channel,
-    ]);
+
+    const result = await exec.getExecOutput('charmcraft', ['pack']);
```
[the remark this answers is not in the document]
Comment (mvlassis) [reply src/services/bundle/bundle.ts:9]: Smart, that's better practice

File: src/services/bundle/bundle.ts [hunk 3]
```diff
@@ -5,13 +5,28 @@ class Bundle {
...
+      } else {
+        throw new Error(
+          'Failed to extract the bundle name from the output of charmcraft pack.',
+        );
+      }
+    } else {
+      throw new Error(
+        `charmcraft pack ran unsuccessfully with exit code ${result.exitCode}.`,
+      );
+    }
```
[the remark this answers is not in the document]
Comment (mvlassis) [reply src/services/bundle/bundle.ts:29]: Interesting read, in this case I think using negative conditionals increases legibility

File: src/services/bundle/bundle.ts (hunk 1 above)
Comment (orfeas-k) [reply src/services/bundle/bundle.ts]: >This means that this error should never be reached, but the if else block is required because otherwise compiling the TypeScript produces an error. 

Yes +1. What you could do is if(!lastLine){ throwError..} and then the rest of the code as you did with the other `if..else` statement. But that's a nit. Feel free to keep the `if..else` if you like that better. 

>But then again, I am not 100% sure that output is always produced on stderr.

I played around a bit and indeed, I couldn't find a case where sth was produced in stdout. We can always ask a question in charmcraft channel just to verify this. WDYT?

>Is there a more appropriate structure for this situation in TypeScript? I'm thinking something like the "?" operator or the "unwrap()" function that exists in Rust.

There's this [operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_operator) but I think that using an if here is more than fine. My conern was regarding the message but since "the command should always output at least 1 non-empty line to stderr", then this LGTM.

Comment (mvlassis) [reply src/services/bundle/bundle.ts]: Ok, turns out that as of the time of writing, `charmcraft pack` uses a `progress` function that always outputs the message to stderr. Specifically, it's in [these lines](https://github.com/canonical/craft-application/blob/276d4f375e0607f6c46dd283798cc4d11a3537f3/craft_application/commands/lifecycle.py#L378-L384). In this case, working with stderr is OK (at least until [this issue](https://github.com/canonical/craft-application/issues/434) is completed).
